AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: true
  SuggestExtensions: false

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/CommentIndentation:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true
